[profile.default]
src="src/"
out = "out"
libs = ["lib"]

remappings=["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.core]
src="src/core/"
solc="0.8.20"

[profile.uniswap]
src="src/uniswap-v2/"
solc="0.5.16"
test="src/uniswap-v2/test"